// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnnryucifucnvcjfpzsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBubnJ5dWNpZnVjbnZjamZwenNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDYwOTYsImV4cCI6MjA2NDY4MjA5Nn0.FUxOAvDxY2g3OvcX2TC-EfarATYlsuJmUdj_YT3_jb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);